### ISSUE TITLE
Changing mysql User password, instead of creating a new one

### ISSUE THREAD

**Issue by adshrc** [bitnami/bitnami-docker-joomla#15]
Hi,

when using multiple instances (accessing the same database), the installer creates a new database with a random suffix, but using the same user (bn_joomla). It just changes his password, so that previously created instances get an mysql-connect-error.

**Comment by chipironcin** [comment]
Hi @unrl 
First of all, thanks for reporting it.

Currently, we only support the scenario with one instance of the same application for a single database.
As we are already creating a unique database name we will revisit this soon and check if we are able to support your scenario.
Meanwhile, I suggest you the following:
  - Deploy your first Joomla.
  - Change joomla username in database and joomla config file
  - Deploy your second joomla
This way the first Joomla will use the database username `bn_jooomla_1` and the second Joomla will use `bn_joomla`.

I will keep this issue open so more people can request this specific scenario and will reconsider to support it.
Regards, Jorge

**Comment by xoroz** [comment]
I would like to do the same here. Allow multiple instances of joomla and one single DB.
I keep getting 

1/29/2019 5:31:35 PMError executing 'postInstallation': File /opt/bitnami/joomla/installation/sql/mysql/joomla.sql did not match any of the provided substitutions

Guess I will have to clone the image and review the startup script, it should just check if the DB already exists, if so don't do anything, right? Does not seem difficult to do...

Was anybody able using multiple instances? 
I am using RancherOS cattle enviroment and you guys can use my rancher catalog from here:
https://gitlab.iit.it/fferreira/iit-rancher-catalog

**Comment by javsalgar** [comment]
Hi,

I was able to make it work with this example docker-compose file

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_joomla
      - MARIADB_DATABASE=bitnami_joomla
  joomla:
    image: 'bitnami/joomla:latest'
    environment:
      - JOOMLA_DATABASE_USER=bn_joomla
      - JOOMLA_DATABASE_NAME=bitnami_joomla
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
  joomla2:
    image: 'bitnami/joomla:latest'
    environment:
      - JOOMLA_DATABASE_USER=bn_joomla_2
      - JOOMLA_DATABASE_NAME=bitnami_joomla_2
      - JOOMLA_DATABASE_PASSWORD=testtest
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_joomla_2
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla_2
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=testtest
    depends_on:
      - mariadb
    ports:
      - '81:80'
      - '444:443'
```

It should work with persistence as well.
