### ISSUE TITLE
error on  joomla bitnami: ERROR 1364 (HY000) at line 1

### ISSUE THREAD

**Issue by plhmk** [bitnami/bitnami-docker-joomla#66]
**Description**
I have this error when try run following .yml file

**Steps to reproduce the issue:**
I use this .yml file

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '8080:80'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  drupal:
    image: 'bitnami/drupal:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_drupal
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8081:80'
    volumes:
      - 'drupal_data:/bitnami'
    depends_on:
      - mariadb
  joomla:
    image: 'bitnami/joomla:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_joomla
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_joomla
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8082:80'
    volumes:
      - 'joomla_data:/bitnami'
    depends_on:
      - mariadb
  owncloud:
    image: 'bitnami/owncloud:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_owncloud
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8083:80'
    volumes:
      - 'owncloud_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  drupal_data:
    driver: local
  joomla_data:
    driver: local
  owncloud_data:
    driver: local
```

**Describe the results you received:**

All run correctly but i have this error on Joomla only:

Error executing 'postInstallation': MySQL command failed to run. Error: 

 ERROR 1364 (HY000) at line 1: Field 'params' doesn't have a default value

ERROR 1364 (HY000) at line 1: Field 'params' doesn't have a default value

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
```
- Output of `docker version`:
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        e8ff056
 Built:             Thu May  9 23:11:19 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e8ff056
  Built:            Thu May  9 22:59:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
- Output of `docker info`:
Containers: 6
 Running: 5
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-50-generic
Operating System: Linux Mint 19
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.37GiB
Name: pl-antec-mint
ID: YKLG:IBTK:6MAN:ESRH:RLLI:UOPN:GQN2:OBXJ:OHKQ:ZC2P:YD3W:ITMA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
- Output of `docker-compose version` (if applicable):
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
