### ISSUE TITLE
Error message when MARIADB_PASSWORD and JOOMLA_DATABASE_PASSWORD are included

### ISSUE THREAD

**Issue by pekechis** [bitnami/bitnami-docker-joomla#73]
**Environment**
Ubuntu 20.04
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.0, build unknown

The default docker-compose.yml runs smoothly but when added password environment var for the DB service the browser is showing an "Error".

```yaml

version: '2' 
services:   
  servicio1:
    container_name: 'contenedor1' 
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'     
    ports:
        - '3336:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=juan
      - MARIADB_PASSWORD=juan
      - MARIADB_DATABASE=bd_joomla
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  servicio2:
    container_name: 'contenedor2'
    image: 'docker.io/bitnami/joomla:3-debian-10'
    ports:
      - '8181:8080'
      - '443:8443'
    environment:
      - JOOMLA_DATABASE_HOST=servicio1
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_USER=juan
      - JOOMLA_DATABASE_PASSWORD=juan
      - JOOMLA_DATABASE_NAME=bd_joomla
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'joomla_data:/bitnami/joomla'
    depends_on:
      - servicio1
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
```

The DB service, even when the password is specified is showing the following message:

contenedor1  | 2020-10-20 20:53:12 21 [Warning] Access denied for user 'juan'@'172.30.0.3' (using password: NO)

And the Joomla Service is showing session waring message:
PHP Warning:  session_start(): Failed to read session data: user (path: ) in /bitnami/joomla/libraries/joomla/session/handler/native.php

No problems arise when MARIADB_PASSWORD and JOOMLA_DATABASE_PASSWORD are removed from docker-compose.yml

Thanks in advance
